### ISSUE TITLE
Forse close on Poweramp volume panel showing + custom skin enabled

### ISSUE THREAD

**Issue by RznNike** [maxmpz/powerampapi#11]
How to reproduce:
- build, install, apply custom skin (clean sample skin enough)
- enable custom volume panel in Poweramp settings
- try to change volume by pressing button

Messages about same problem started from here: https://4pda.ru/forum/index.php?s=&showtopic=840939&view=findpost&p=76640860

Logcat:
`09-02 21:20:06.856 2269-2536/? I/vol.Events: writeEvent level_changed STREAM_MUSIC 7
09-02 21:20:06.866 28809-28809/? I/zygote: Deoptimizing android.content.res.TypedArray android.content.res.TypedArray.obtain(android.content.res.Resources, int) due to JIT inline cache
    Deoptimizing void android.view.ViewGroup.initFromAttributes(android.content.Context, android.util.AttributeSet, int, int) due to JIT inline cache
09-02 21:20:06.880 28809-28809/? D/AndroidRuntime: Shutting down VM
09-02 21:20:06.881 28809-28809/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.maxmpz.audioplayer, PID: 28809
    android.view.InflateException: Binary XML file line #22: Binary XML file line #22: You must supply a layout_width attribute.
    Caused by: java.lang.UnsupportedOperationException: Binary XML file line #22: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:775)
        at android.content.res.XResources$XTypedArray.getLayoutDimension(XResources.java:1435)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7554)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7746)
        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:368)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:502)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
        at android.view.LayoutInflater.inflate(<Xposed>)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
        at android.app.Dialog.setContentView(Dialog.java:528)
        at nm.l1l1(":111)
        at nm$null.handleMessage(":295)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
09-02 21:20:06.916 1890-12950/? W/ActivityManager:   Force finishing activity com.maxmpz.audioplayer/.ListActivity
09-02 21:20:06.943 1890-12950/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:966 com.android.server.am.AppErrors.crashApplicationInner:393 com.android.server.am.AppErrors.crashApplication:321 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:14559 com.android.server.am.ActivityManagerService.handleApplicationCrash:14541 
09-02 21:20:06.948 1890-2002/? I/ActivityManager: Showing crash dialog for package com.maxmpz.audioplayer u0`

**Comment by maxmpz** [comment]
That is fixed in build 796.

-- 
- Maksim Petrov


RznNike wrote:

**Comment by bighead9971-ux** [comment]
![47b9c7921ce7493e81421b454d6bf4554ce9942d36ce6aac8f0c3f9dc131edb5_260508220832.png](https://github.com/user-attachments/assets/9065e75e-60a9-49cb-98ed-366e3a7d4824)
