### ISSUE TITLE
FC when launching skin template for v3 

### ISSUE THREAD

**Issue by gcantoni** [maxmpz/powerampapi#9]
Logcat:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.poweramp.blackred, PID: 21587
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.poweramp.blackred/com.poweramp.sampleskin.SkinInfoActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x50000
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x50000
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2148)
        at android.content.res.Resources.getLayout(Resources.java:1157)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:461)
        at android.app.Activity.setContentView(Activity.java:2737)
        at com.poweramp.sampleskin.SkinInfoActivity.onCreate(SkinInfoActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `

**Comment by maxmpz** [comment]
- do you able to start unmodified (just checked out) skin?
- what is your Android studio version and Android SDK tools version?
- sample skin has no resource 0x50000. Can you search your project for this constant (R.java)? What is that?

**Comment by maxmpz** [comment]
I can reproduce this issue with your commit, reverting back to com.android.tools.build:gradle:3.1.4 as it works. You may need to do this: https://stackoverflow.com/questions/49990933/configuration-on-demand-is-not-supported-by-the-current-version-of-the-android-g

**Comment by gcantoni** [comment]
Thank you! A possible fix is to add instantly the path where the APK of Poweramp is placed! Is there a way to get in contact with you? I have 90% finished my skin but I have not idea where do find some things. Thank you!

**Comment by maxmpz** [comment]
PM me @ forum.powerampapp.com

**Comment by gcantoni** [comment]
@maxmpz i'm not able to join in forum ( there is probably a bug when you ask age ). Could you contact me via email ? giorgio.canto98@gmail.com

**Comment by maxmpz** [comment]
Hello,

what is the exactly error you're seeing on forum? We have like 100+ 
registrations a day, never heard about issue with age.

Thanks!
-- 
- Maksim Petrov


Giorgio Cantoni wrote:

**Comment by gcantoni** [comment]
@maxmpz the issue was automatically fixed. Probably lot of traffic on the server. I sent you a PM!
